CREATE DATABASE IF NOT EXISTS blackvs;
USE blackvs;

CREATE TABLE IF NOT EXISTS sites (
  id CHAR(36) PRIMARY KEY,
  domain VARCHAR(253) NOT NULL UNIQUE,
  root_path VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
